### PR TITLE
Added API to generate statistics regularly.

### PR DESCRIPTION
**Pull request by keshavnangare**
Please find the below issue for more info:

https://github.com/opengeospatial/teamengine-statistics/issues/14

https://github.com/opengeospatial/teamengine-statistics/issues/15

### CODE REVIEW

**Comment by ghobona** [comment]
@keshav-nangare The endpoint that triggers the statistics calculation needs to be protected with TEAM Engine's access control/login capability (or HTTP Authentication). This would reduce the risk of becoming a target of a DDOS attack.

**Comment by keshav-nangare** [comment]
The endpoint is already secured using basic authentication mechanism. Please find the changes in the branch `basic-authentication`.

**Comment by keshav-nangare** [comment]
Added changes to access statistics report by Admin only and restrict other user with role. Please find the changes in the `basic-authentication` branch with commit id https://github.com/opengeospatial/teamengine/commit/3c8272033ae459ac658698b1e218d65c41c68a78

**Comment by keshav-nangare** [comment]
The change related to secure te-statistics api are present in that PR #433.
This PR should be merged after basic_authentication PR: https://github.com/opengeospatial/teamengine/pull/433 is merged.

**Comment by dstenger** [comment]
@keshav-nangare Can you please create documentation in site folder of TEAM Engine?

This shall include:
* How to access the te-statistics report from the cite directory.
* For #433 please document, how to become admin.

**Comment by keshav-nangare** [comment]
@dstenger 

I have updated the documentation as per the above comment.

**Comment by dstenger** [comment]
@keshav-nangare Can you please move the documentation to the site folder?

**Comment by keshav-nangare** [comment]
@dstenger

I have updated the documentation.

**Review by bpross-52n — APPROVED** [review]

**Comment by dstenger** [comment]
@bpross-52n Can you please do a short test checking the roles mechanism? A regular user should not be able to use the new functionality. A user with role admin should be able to use it.

**Pull request merged**
