### PR TITLE
Added headless form support, removed unecessary casts, centralized access to args[i] into a single local variable

### PR DESCRIPTION
**Pull request by aaime**

### CODE REVIEW

**Comment by aaime** [comment]
Any feedback?

**Comment by bermud** [comment]
@aaime, can you please also provide example test files and example of how to run it? Thank you very much.

**Comment by aaime** [comment]
I sure can. Should I add that to the tutorial page here?
https://github.com/opengeospatial/teamengine/blob/master/doc/en/index.rst

**Comment by bermud** [comment]
Yes that will be great. Thank you. I can test right away.

**Comment by aaime** [comment]
I'll try to update the pull request next weekend (this is not sponsored work, so I'm limited to spare time)

**Comment by aaime** [comment]
Pull request updated with docs on how to use the form files, and how to build their contents.

**Comment by bermud** [comment]
@aaime, thank you very much for providing further details about how to run in headless mode. I tried 9b86fd7c pull request, but I'm getting this error. Do we need to do anything on the CTL tests or?

```
Fatal Error: Error: Unable to bind function functions:append-kvp; SystemID: file:/Users/lbermudez/te-build/catalina_base/TE_BASE/work/_Users_lbermudez_te-build_catalina_base_TE_BASE_scripts_wms_1.1.1_ctl_wms.xml/wms$wms_main.test; Line#: 147; Column#: -1
Jul 12, 2015 6:23:17 AM com.occamlab.te.TECore executeTest
SEVERE: Error: Unable to bind function functions:append-kvp
   Test wms:wms_main Failed
			See the detail test Report /Users/lbermudez/te-build/catalina_base/TE_BASE/users/lbermudez/s0003/log.xml
			See the detail error Report /Users/lbermudez/te-build/catalina_base/TE_BASE/users/lbermudez/s0003/error_log/log.txt
```

Here is the error_log/log.txt from the users folder

```

2015/07/12-06:23:17 ERROR
Test Name : wms:wms_main type Mandatory
net.sf.saxon.s9api.SaxonApiException: Error: Unable to bind function functions:append-kvp
	at net.sf.saxon.s9api.XsltTransformer.transform(XsltTransformer.java:192)
	at com.occamlab.te.TECore.executeTemplate(TECore.java:571)
	at com.occamlab.te.TECore.executeTest(TECore.java:779)
	at com.occamlab.te.TECore.execute_test(TECore.java:390)
	at com.occamlab.te.TECore.execute_suite(TECore.java:438)
	at com.occamlab.te.TECore.execute(TECore.java:295)
	at com.occamlab.te.Test.execute(Test.java:318)
	at com.occamlab.te.Test.main(Test.java:91)
Caused by: net.sf.saxon.trans.XPathException: Error: Unable to bind function functions:append-kvp
	at com.occamlab.te.saxon.TEJavaFunctionCall.iterate(TEJavaFunctionCall.java:51)
	at net.sf.saxon.instruct.SimpleContentConstructor.evaluateItem(SimpleContentConstructor.java:270)
	at net.sf.saxon.instruct.ValueOf.evaluateItem(ValueOf.java:251)
	at net.sf.saxon.instruct.SimpleNodeConstructor.iterate(SimpleNodeConstructor.java:219)
	at net.sf.saxon.instruct.DocumentInstr.evaluateItem(DocumentInstr.java:245)
	at net.sf.saxon.expr.ExpressionTool.evaluate(ExpressionTool.java:295)
	at net.sf.saxon.expr.LetExpression.eval(LetExpression.java:341)
	at net.sf.saxon.expr.LetExpression.processLeavingTail(LetExpression.java:542)
	at net.sf.saxon.instruct.Block.processLeavingTail(Block.java:409)
	at net.sf.saxon.instruct.Instruction.process(Instruction.java:94)
	at net.sf.saxon.expr.LetExpression.process(LetExpression.java:380)
	at net.sf.saxon.instruct.ForEach.processLeavingTail(ForEach.java:300)
	at net.sf.saxon.expr.LetExpression.processLeavingTail(LetExpression.java:551)
	at net.sf.saxon.instruct.Block.processLeavingTail(Block.java:409)
	at net.sf.saxon.instruct.Block.processLeavingTail(Block.java:409)
	at net.sf.saxon.instruct.Block.processLeavingTail(Block.java:409)
	at net.sf.saxon.instruct.Block.processLeavingTail(Block.java:409)
	at net.sf.saxon.instruct.Block.processLeavingTail(Block.java:409)
	at net.sf.saxon.instruct.Block.processLeavingTail(Block.java:409)
	at net.sf.saxon.instruct.Block.processLeavingTail(Block.java:409)
	at net.sf.saxon.instruct.Block.processLeavingTail(Block.java:409)
	at net.sf.saxon.instruct.Block.processLeavingTail(Block.java:409)
	at net.sf.saxon.instruct.Block.processLeavingTail(Block.java:409)
	at net.sf.saxon.expr.LetExpression.processLeavingTail(LetExpression.java:551)
	at net.sf.saxon.instruct.Block.processLeavingTail(Block.java:409)
	at net.sf.saxon.expr.LetExpression.processLeavingTail(LetExpression.java:551)
	at net.sf.saxon.instruct.Block.processLeavingTail(Block.java:409)
	at net.sf.saxon.instruct.Block.processLeavingTail(Block.java:409)
	at net.sf.saxon.instruct.Block.processLeavingTail(Block.java:409)
	at net.sf.saxon.instruct.Instruction.process(Instruction.java:94)
	at net.sf.saxon.expr.LetExpression.process(LetExpression.java:380)
	at net.sf.saxon.instruct.ForEach.processLeavingTail(ForEach.java:300)
	at net.sf.saxon.expr.LetExpression.processLeavingTail(LetExpression.java:551)
	at net.sf.saxon.instruct.Template.applyLeavingTail(Template.java:175)
	at net.sf.saxon.instruct.ApplyTemplates.applyTemplates(ApplyTemplates.java:343)
	at net.sf.saxon.Controller.transformDocument(Controller.java:1736)
	at net.sf.saxon.Controller.transform(Controller.java:1560)
	at net.sf.saxon.s9api.XsltTransformer.transform(XsltTransformer.java:190)
	... 7 more
Caused by: java.lang.ClassNotFoundException: com.occamlab.ctlfns.JaxenFunction
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at com.occamlab.te.TEClassLoader.loadClass(TEClassLoader.java:130)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:274)
	at com.occamlab.te.util.Misc.getMethod(Misc.java:118)
	at com.occamlab.te.util.Misc.getMethod(Misc.java:141)
	at com.occamlab.te.saxon.TEJavaFunctionCall.iterate(TEJavaFunctionCall.java:48)
	... 44 more



```

**Comment by aaime** [comment]
I've seen similar errors when not adding the necessary dependency jars in the te_base directory. JaxenFunction is is ``cite1-utils-*.jar``, which is part of ``ets-wms11-1.10-deps.zip``, that should be unzipped in ``${te_base}/resources/lib``. Can you check if it's there?

**Comment by bermud** [comment]
That jar was missing. Your solution worked perfectly nice. Thank you for making the changes to the code and making the explanation.

**Pull request merged**
