### PR TITLE
Feature issue190

### PR DESCRIPTION
**Pull request by rjmartell**
Generate EARL results from CTL results.

### CODE REVIEW

**Comment by rjmartell** [comment]
After running the WMS 1.3 test suite, the generated earl-results.rdf file doesn't include much info.
```
<rdf:RDF
    xmlns:dct="http://purl.org/dc/terms/"
    xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
    xmlns:http="http://www.w3.org/2011/http#"
    xmlns:cnt="http://www.w3.org/2011/content#"
    xmlns:earl="http://www.w3.org/ns/earl#"
    xmlns:cite="http://cite.opengeospatial.org/">
  <earl:TestSubject rdf:about="inut=41"/>
  <earl:Assertor rdf:about="https://github.com/opengeospatial/teamengine">
    <dct:title xml:lang="en">OGC TEAM Engine</dct:title>
    <dct:description xml:lang="en">Official test harness of the OGC conformance testing program (CITE).</dct:description>
  </earl:Assertor>
  <cite:TestRun>
    <dct:title>OGC-SampleTest</dct:title>
    <dct:created>2016-11-15T23:44:37.139Z</dct:created>
    <cite:requirements>
      <rdf:Seq/>
    </cite:requirements>
  </cite:TestRun>
</rdf:RDF>
```

**Comment by keshav-nangare** [comment]
Hi Richard,

The earl report is not containing the information because the wms13 test-suite is not updated / refactored according to the conformance class, means we need to add attribute `isConformanceClass="true" isBasic="true"` into ctl:test then it will considered as conformance class.

```
For example:

<ctl:test name="ex:is-even-A" isConformanceClass="true" isBasic="true">
	<ctl:assertion>The test for A.</ctl:assertion>
	<ctl:code/>
  </ctl:test>
```

**Comment by rjmartell** [comment]
What does isBasic mean? That it's a mandatory conformance class?

**Comment by keshav-nangare** [comment]
"isBasic" is attribute which represent the basic conformance classes nothing else.

If test is conformance class but not basic tests then it will false or if test is conformance class and basic then it will be true.

Here is issue #45 which will gives the better description.

**Pull request merged**
