### PR TITLE
Updated all dependencies to the latest versions

### PR DESCRIPTION
**Pull request by vishalsingh2972**

### CODE REVIEW

**Comment by dstenger** [comment]
Thank you for providing the pull request.
What Java version did you use to test the build (mvn clean install site)? I get errors with both, Java 8 and Java 17.

**Review by dstenger — CHANGES_REQUESTED** [review]
Thank you for providing the pull request.
What Java version did you use to test the build (mvn clean install site)? I get errors with both, Java 8 and Java 17.
Also, we already did some updates on branch `6.0` which is the working branch of the issues.

**Comment by vishalsingh2972** [comment]
> Thank you for providing the pull request. What Java version did you use to test the build (mvn clean install site)? I get errors with both, Java 8 and Java 17. Also, we already did some updates on branch `6.0` which is the working branch of the issues.

I used JDK 17. If updates are already implemented is there anything else that I can help with as I see the issue is still open?

**Comment by dstenger** [comment]
Thank you again for providing the pull request.
Unfortunately, we can only accept PRs which are building with `mvn clean install site`. Also, the target branch is `6.0` in this case.

**Pull request closed without merging**
