### PR TITLE
Console application updates

### PR DESCRIPTION
**Pull request by cmorriscmps**
This pull request includes these changes, which help with using TEAM Engine from the command line.

- Moved the ConfigFileCreator class and its dependencies from teamengine-web to teamengine-core.
	com.occamlab.te.web.ConfigFileCreator -> com.occamlab.te.config.ConfigFileCreator
	com.occamlab.te.web.Config and com.occamlab.te.vocabulary.Config -> com.occamlab.te.config.Config
	com.occamlab.te.web.TEException -> com.occamlab.te.config.TEConfigException
	com.occamlab.te.web.TEBaseNotFoundException -> com.occamlab.te.config.TEBaseNotFoundException
	com.occamlab.te.web.XMLUtils -> com.occamlab.te.util.XMLUtils
- Added a main method to ConfigFileCreator so it can be called from the command line.
- Restored the original doc mode behavior in Test.java, which visits all subtests and generates log files without executing them.
- Moved the entry point for the PseudoCTLDocumentation generator (which was called in Test.java with -mode=doc) to a new main method in DocumentationHelper.
- Moved the entry point for the PrettyPrint functionality (which was called in Test.java with -mode=pplogs) to the main method of ViewLog.  It is activated with the -pp parameter.
- Added the ability to generate EARL and HTML reports of sessions to the main method of ViewLog.  It is activated with the -html parameter.
- Documented the doc, cache, and check modes in Test.java.
- Updated Test.java and ViewLog.java so the -logdir option is not required.  It will now default to the users dir in $TE_BASE.
- Updated ListSuites.java so -source options are not required.  It will use all sources in the master config file if no -source options are provided.

### CODE REVIEW

**Comment by dstenger** [comment]
@cmorriscmps Thank you for providing the pull request.
Can you please provide some examples/ use cases how the changes introduced by this pull request can be used?

**Comment by cmorriscmps** [comment]
@dstenger I think that the best way for me to provide examples/ use cases would be to update the "command shell" section of the user's guide at https://opengeospatial.github.io/teamengine/users.html.  Can you point me to the source code for that page, or instructions on how to update it?

**Comment by dstenger** [comment]
@cmorriscmps Sure, the file is located here: https://github.com/opengeospatial/teamengine/blob/master/src/site/markdown/users.md
You are welcome to include an update of this file into this pull request.

**Comment by cmorriscmps** [comment]
@dstenger Pull request has been updated and is ready for review.

**Comment by dstenger** [comment]
@bpross-52n please include tests of following components in your review:
* Web Browser Interface
* REST Interface
* Command Line Interface

**Review by bpross-52n — APPROVED** [review]

**Comment by dstenger** [comment]
When starting this pull request with [teamengine-docker project](https://github.com/opengeospatial/teamengine-docker) (teamengine-beta), I get the following error when trying to log in via Web Browser Interface:
```
SEVERE: Servlet.service() for servlet [jsp] in context with path [/te2] threw exception [Unable to compile class for JSP: 

An error occurred at line: 7 in the jsp file: /viewSessions.jsp
Config cannot be resolved to a type
4:   session="false"
5:   import="java.io.File, javax.xml.parsers.*, java.util.Arrays, com.occamlab.te.web.*, java.util.List, java.util.ArrayList"
6: %><%!
7:   Config Conf;
8:   DocumentBuilder DB;
9:   List<TestSession> testData;
10: 
...
Stacktrace:
	at org.apache.jasper.compiler.DefaultErrorHandler.javacError(DefaultErrorHandler.java:103)
	at org.apache.jasper.compiler.ErrorDispatcher.javacError(ErrorDispatcher.java:366)
	at org.apache.jasper.compiler.JDTCompiler.generateClass(JDTCompiler.java:590)
	at org.apache.jasper.compiler.Compiler.compile(Compiler.java:379)
	at org.apache.jasper.compiler.Compiler.compile(Compiler.java:354)
	at org.apache.jasper.compiler.Compiler.compile(Compiler.java:341)
	at org.apache.jasper.JspCompilationContext.compile(JspCompilationContext.java:660)
	at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:395)
	at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:395)
	at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:339)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:110)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:603)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:169)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:104)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:1025)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:445)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1137)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:637)
	at org.apache.tomcat.util.net.AprEndpoint$SocketProcessor.doRun(AprEndpoint.java:2575)
	at org.apache.tomcat.util.net.AprEndpoint$SocketProcessor.run(AprEndpoint.java:2564)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:750)
```

**Comment by cmorriscmps** [comment]
I think the error in viewSessions.jsp should be fixed now.

**Comment by dstenger** [comment]
@cmorriscmps Thanks for the update. I can confirm that the error does not occur anymore.

**Review by dstenger — APPROVED** [review]
I did some smoke tests including:
- Web Browser Interface
   - All major functionalities seem to work as expected.
- REST Interface
   - All major functionalities seem to work as expected.
-  Command Line Interface
   - Documentation was reviewed.
   - New scripts were tested.
   - All major functionalities seem to work as expected.

**Pull request merged**
